#!/bin/bash

DJANGODIR=/webapps/jatte/jatte
DJANGO_SETTINGS_MODULE=jatte.settingsprod

cd $DJANGODIR
source ../env/bin/activate
export DJANGO_SETTINGS_MODULE=$DJANGO_SETTINGS_MODULE
export PYTHONPATH=$DJANGODIR:$PYTHONPATH

daphne -b 0.0.0.0 -p 8002 jatte.asgi:application
